language: haskell

ghc:
  - 7.8
  - 7.6
# - 7.4

script:
  # Option -fpedantic turns on additional wornings in addition to -Wall.
  - cabal configure -fpedantic --enable-tests && cabal build && cabal test --show-details=always

  # Following line tests if sdist package is created correctly.
  - cabal sdist && cabal install --enable-tests dist/lock-file-*.tar.gz
